# =============================================================================
# Fortress Backup Manager - Production Dockerfile
# =============================================================================
# Multi-stage build for optimal image size
# Uses Bun for both build and runtime (bun:sqlite native support)
# Includes: Borg, Restic, Rclone, SSH client for backup operations
# =============================================================================

# -----------------------------------------------------------------------------
# Stage 1: Builder - Install dependencies and build frontend
# -----------------------------------------------------------------------------
FROM oven/bun:1-alpine AS builder

WORKDIR /app

# Copy package files first for better layer caching
COPY package.json bun.lock ./

# Install all dependencies (including devDependencies for build)
RUN bun install --frozen-lockfile

# Copy source code
COPY . .

# Build the frontend
RUN bun run build

# -----------------------------------------------------------------------------
# Stage 2: Production - Bun runtime with bun:sqlite
# -----------------------------------------------------------------------------
FROM oven/bun:1-alpine AS production

WORKDIR /app

# Install runtime dependencies:
# - Backup tools: borgbackup, restic, rclone
# - SSH client for remote backup operations
# - wget for healthchecks
# - tzdata for timezone support
# - su-exec for dropping privileges in entrypoint
RUN apk add --no-cache \
    borgbackup \
    restic \
    rclone \
    openssh-client \
    wget \
    tzdata \
    su-exec \
    && rm -rf /var/cache/apk/*

# Copy package files and install production dependencies only
COPY package.json bun.lock ./
RUN bun install --production --frozen-lockfile && \
    rm -rf /root/.bun/install/cache

# Copy built frontend from builder stage
COPY --from=builder /app/dist ./dist

# Copy server code and configuration
COPY server ./server
COPY tsconfig.json ./
COPY types.ts ./

# Copy and setup entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Create required directories with proper permissions
RUN mkdir -p /app/data /app/logs && \
    chmod 777 /app/data /app/logs

# Create non-root user for security
RUN addgroup -g 1001 -S bunjs && \
    adduser -S bunjs -u 1001 -G bunjs && \
    chown -R bunjs:bunjs /app

# Environment variables (minimal - rest generated by setup page)
ENV NODE_ENV=production
ENV PORT=9001

# Expose the application port
EXPOSE 9001

# Note: Container starts as root, entrypoint switches to bunjs after fixing permissions

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD wget -q --spider http://localhost:9001/api/health || exit 1

# Entrypoint script ensures data directory is writable
ENTRYPOINT ["docker-entrypoint.sh"]

# Start with native Bun (bun:sqlite built-in)
CMD ["bun", "start"]
